### ISSUE TITLE
Heroku - Reference Time Incorrect

### ISSUE THREAD

**Issue by jkcaldwe** [seekingvega/marketclock#1]
I have been using the Heroku application with Python and noticed the time and date is often incorrect. A few times the 'ref_date_time' showed the date to be yesterday. It now shows the time incorrectly
![Screenshot 2022-06-10 121348](https://user-images.githubusercontent.com/20329866/173044332-f475fd8f-75dd-4094-a95e-f56d3d00d3b0.png)
.

**Comment by ohjho** [comment]
hey @jkcaldwe thanks for the nice catch! the datetime object used by the `exchanges/{exchange}` endpoint is stall! I have fixed this and redeployed to Heroku

For reference, `ref_date_time` is the current time (time of the API request) in the relevant exchange timezone, in your case `America/New_York`
